import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {TooltipProvider} from "@/components/ui/tooltip"
import { Toaster } from "sonner";
import { JotaiProvider } from "@/components/providers/jotai-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${geistSans.style} ${geistMono.variable} antialiased`}
      >
                <JotaiProvider>
        <TooltipProvider>
          <Toaster toastOptions={
            {className: "rounded-none border-0"}
          }/>
          {/* TODO: Remove React Query devtools */}
        {children}
        </TooltipProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
